### ISSUE TITLE
Error "FFmpeg exited with code: 1 and signal: null (Error) Front Door Doorbell"

### ISSUE THREAD

**Issue by nefariouslegion** [homebridge/ffmpeg-for-homebridge#58]
Tbh not sure if I should post this here or not. I've also posted it on the plugin page but haven't gotten a fix yet.

**Describe The Bug:**
Whenever I try to view my camera in the home app I see the error "FFmpeg exited with code: 1 and signal: null (Error) Front Door Doorbell" in the homebridge logs. The home app just shows "No response"

**Expected behavior:**
Expected to have ffmpeg working and be able to view camera 

**ffmpeg output:**

Run `ffmpeg` in a terminal window and post the output below
Here is what the homebridge UI terminal outputs when I enter the command. 
![image](https://github.com/homebridge/ffmpeg-for-homebridge/assets/89366675/9487e64c-e9fc-4151-8611-bf627c98010a)

And here is what the hyper-v VM outputs when trying to enter the same command there
![image](https://github.com/homebridge/ffmpeg-for-homebridge/assets/89366675/a8e34a50-3c3a-40a8-ac4e-7758e3ce301c)

**Screenshots:**
See above.

**Environment:**

* **Operating System**: Ubuntu (I think?) The Homebridge UI System Information says "OS: Ubuntu Focal Fossa (20.04.5 LTS)>

**Comment by bwp91** [comment]
Hi @nefariouslegion 

Apologies you never had a reply on this.

Since this issue is not necessarily applicable to the newest version of ffmpeg-for-homebridge I am gonna close this.

My advice would be to start using the newest version of ffmpeg-for-homebridge and if you still encounter the above, and feel it is an issue with this repo then please do reopen again.

Cheers!
